#!/bin/sh
# Prepares the local Flutter defines for an Xcode Run/Archive.
#
# Xcode does not execute run_with_keys.sh or run_release_with_keys.sh. The
# shared Runner scheme invokes this script before Flutter's own build action so
# Archive uses the same local values when secrets.local.properties exists.
# The generated xcconfig is ignored and is never committed.
#
# Supabase's production URL/publishable key are compiled into Dart as a safe
# fallback, so this script is optional for a clean checkout. The local file is
# still used for private provider credentials that must not be committed.
set -eu

IOS_DIR=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
APP_DIR=$(CDPATH= cd -- "$IOS_DIR/.." && pwd)
SECRETS_FILE="$APP_DIR/secrets.local.properties"
OUTPUT_FILE="$IOS_DIR/Flutter/XcodeSecrets.xcconfig"
TEMP_FILE="$OUTPUT_FILE.tmp"

property() {
  key="$1"
  if [ -f "$SECRETS_FILE" ]; then
    awk -F= -v wanted="$key" '$1 == wanted {sub(/^[^=]*=/, ""); print; exit}' "$SECRETS_FILE"
  fi
}

encode_define() {
  printf '%s' "$1=$2" | base64 | tr -d '\n'
}

# Keep Flutter's own generated defines (engine/channel/version) but remove
# stale app defines. The values from secrets.local.properties are appended
# below, so a changed local key replaces the previous generated value.
generated_defines=""
if [ -f "$IOS_DIR/Flutter/Generated.xcconfig" ]; then
  generated_defines=$(awk -F= '/^DART_DEFINES=/ {sub(/^[^=]*=/, ""); print; exit}' "$IOS_DIR/Flutter/Generated.xcconfig")
fi

kept_defines=""
old_ifs=$IFS
IFS=,
for encoded in $generated_defines; do
  [ -n "$encoded" ] || continue
  decoded=$(printf '%s' "$encoded" | base64 -D 2>/dev/null || printf '%s' "$encoded" | base64 -d 2>/dev/null || true)
  case "$decoded" in
    GEMINI_API_KEY=*|OPENROUTER_API_KEY=*|SUPABASE_URL=*|SUPABASE_ANON_KEY=*|GOOGLE_IOS_CLIENT_ID=*|GOOGLE_WEB_CLIENT_ID=*|REVENUECAT_IOS_KEY=*|REVENUECAT_ANDROID_KEY=*|SENTRY_DSN=*|POSTHOG_API_KEY=*|POSTHOG_HOST=*)
      continue
      ;;
  esac
  if [ -n "$kept_defines" ]; then kept_defines="$kept_defines,"; fi
  kept_defines="$kept_defines$encoded"
done
IFS=$old_ifs

defines="$kept_defines"
for key in \
  GEMINI_API_KEY \
  OPENROUTER_API_KEY \
  SUPABASE_URL \
  SUPABASE_ANON_KEY \
  GOOGLE_IOS_CLIENT_ID \
  GOOGLE_WEB_CLIENT_ID \
  REVENUECAT_IOS_KEY \
  REVENUECAT_ANDROID_KEY \
  SENTRY_DSN \
  POSTHOG_API_KEY \
  POSTHOG_HOST; do
  value=$(property "$key")
  [ -n "$value" ] || continue
  encoded=$(encode_define "$key" "$value")
  if [ -n "$defines" ]; then defines="$defines,"; fi
  defines="$defines$encoded"
done

{
  echo "// Generated by prepare_xcode_config.sh; do not commit."
  if [ -n "$defines" ]; then
    echo "DART_DEFINES = $defines"
  fi
} > "$TEMP_FILE"
mv "$TEMP_FILE" "$OUTPUT_FILE"

if [ -f "$SECRETS_FILE" ]; then
  echo "Xcode Flutter configuration prepared from secrets.local.properties."
else
  echo "No secrets.local.properties found; using public Supabase defaults and optional integrations remain unconfigured."
fi
