import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart' show debugPrint;
import 'package:path_provider/path_provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:web_socket_channel/web_socket_channel.dart';

import '../models/tutor_persona.dart';
import 'ai_cost_tracker.dart';
import 'gemini_live_service.dart';
import 'gemini_live_token_service.dart';

/// Resolves short tutor audio clips through the same Gemini Live model and
/// selected persona used by an actual call. Generated lesson audio never
/// silently switches to a different voice or to the old HTTP TTS endpoint.
class GeminiLiveAudioService {
  GeminiLiveAudioService._();

  static final shared = GeminiLiveAudioService._();

  // Reverted from 2.5 Native Audio back to 3.1 Live, same as
  // gemini_live_service.dart: 2.5 was cheaper on paper, but real-device
  // testing showed it not responding reliably. Quality/reliability wins
  // over cost here.
  static const _model = 'models/gemini-3.1-flash-live-preview';
  static const _bucket = 'vocabulary-audio';
  // v2 invalidates clips generated with the old conversational persona
  // prompt. Those clips could answer a gratitude sentence instead of reading
  // it, e.g. “De rien…” for “Merci beaucoup pour votre aide.”.
  // v3 invalidated clips generated by the briefly-tried 2.5 Live model.
  // v4 invalidates those v3 (2.5-era) clips now that this has reverted back
  // to 3.1 — a different model can render an identical script audibly
  // differently, so the same cache-consistency reasoning applies on the way
  // back too.
  static const _cacheVersion = 'live-audio-v4';
  static const _storedEncoding = 'pcm_s16le+gzip';
  static const outputSampleRateHz = 24000;

  final Map<String, Future<List<int>?>> _inFlight = {};
  Directory? _cacheDir;

  static String cacheKeyFor({
    required String text,
    required String voiceName,
    bool slow = false,
  }) {
    final normalized = text.trim().replaceAll(RegExp(r'\s+'), ' ');
    return sha256
        .convert(utf8.encode('$_cacheVersion|$voiceName|$slow|$normalized'))
        .toString();
  }

  static String storagePathFor({
    required String userId,
    required String cacheKey,
  }) => '$userId/v1/$cacheKey.pcm';

  /// Gemini 3.1 Live accepts new text turns through realtimeInput. Keeping
  /// this message shape in one place prevents the one-shot pronunciation path
  /// from accidentally using the legacy clientContent turn format.
  static Map<String, dynamic> realtimeTextMessage(String text) => {
    'realtimeInput': {'text': text},
  };

  /// Contract for one-shot lesson/vocabulary pronunciation. This deliberately
  /// excludes the tutor persona prompt: persona instructions describe how to
  /// converse, while this path must read an immutable script and never reply
  /// to its meaning.
  static String pronunciationSystemInstruction({required bool slow}) =>
      'You are an exact French pronunciation renderer, not a conversational '
      'tutor. Treat the realtime text as an immutable script. Speak the '
      'supplied French text word for word, in the same order, exactly once. '
      'Never answer it, acknowledge it, correct it, translate it, explain it, '
      'paraphrase it, or add or omit any words. Do not say anything before or '
      'after the script. ${slow ? 'Use a measured, extra-clear learning pace.' : 'Use a natural, clear learning pace.'}';

  /// Reads an already-generated clip from local storage or the private
  /// Supabase mirror. A playback/cache miss never opens Gemini Live.
  Future<List<int>?> resolve({
    required String text,
    required String contentItemId,
    String? voiceName,
    bool slow = false,
  }) async {
    return loadCached(text: text, voiceName: voiceName, slow: slow);
  }

  /// Generates one clip only as part of an explicit lesson-generation
  /// transaction. Playback screens must never call this method.
  Future<List<int>?> generateAndCache({
    required String text,
    required String contentItemId,
    String? voiceName,
    bool slow = false,
    bool checkRemote = true,
  }) async {
    final normalized = text.trim().replaceAll(RegExp(r'\s+'), ' ');
    if (normalized.isEmpty) return null;
    final persona = _personaForVoice(voiceName);
    if (persona == null) return null;
    final cacheKey = cacheKeyFor(
      text: normalized,
      voiceName: persona.voiceName,
      slow: slow,
    );
    final existing = _inFlight[cacheKey];
    if (existing != null) {
      unawaited(
        AiCostTracker.event(
          feature: contentItemId,
          event: 'audio_generation_deduplicated',
          requestId: cacheKey,
          extra: {'text_length': normalized.length},
        ),
      );
      return existing;
    }
    unawaited(
      AiCostTracker.event(
        feature: contentItemId,
        event: 'audio_generation_requested',
        requestId: cacheKey,
        extra: {'text_length': normalized.length, 'slow': slow},
      ),
    );
    final future = _resolveUnshared(
      normalized,
      contentItemId: contentItemId,
      persona: persona,
      cacheKey: cacheKey,
      slow: slow,
      checkRemote: checkRemote,
    );
    _inFlight[cacheKey] = future;
    try {
      return await future;
    } finally {
      if (identical(_inFlight[cacheKey], future)) _inFlight.remove(cacheKey);
    }
  }

  /// Returns an already-generated clip without ever opening a Gemini Live
  /// socket. This is used by secondary pronunciation controls where a tap
  /// should reuse the lesson's PCM deck, not create new audio on demand.
  Future<List<int>?> loadCached({
    required String text,
    String? voiceName,
    bool slow = false,
  }) async {
    final normalized = text.trim().replaceAll(RegExp(r'\s+'), ' ');
    if (normalized.isEmpty) return null;
    final persona = _personaForVoice(voiceName);
    if (persona == null) return null;
    final cacheKey = cacheKeyFor(
      text: normalized,
      voiceName: persona.voiceName,
      slow: slow,
    );

    // If another screen is already warming this exact clip, wait for that
    // existing work rather than starting anything new from the tap.
    final existing = _inFlight[cacheKey];
    if (existing != null) return existing;

    final local = await _readLocal(cacheKey);
    if (_validPcm(local)) {
      unawaited(
        AiCostTracker.record(
          provider: 'google',
          model: _model,
          feature: 'audio_cache',
          event: 'live_audio_cache_hit_local',
          requestId: cacheKey,
          cacheHit: true,
          extra: {'text_length': text.length},
        ),
      );
      return local;
    }

    final userId = _currentUserId;
    if (userId == null) return null;
    try {
      final remote = await Supabase.instance.client.storage
          .from(_bucket)
          .download(storagePathFor(userId: userId, cacheKey: cacheKey))
          .timeout(const Duration(seconds: 8));
      final bytes = _decodeStored(remote);
      if (!_validPcm(bytes)) return null;
      await _writeLocal(cacheKey, bytes);
      unawaited(
        AiCostTracker.record(
          provider: 'google',
          model: _model,
          feature: 'audio_cache',
          event: 'live_audio_cache_hit_remote',
          requestId: cacheKey,
          cacheHit: true,
          outputAudioSeconds: bytes.length / 2 / outputSampleRateHz,
          extra: {'text_length': normalized.length},
        ),
      );
      return bytes;
    } catch (_) {
      unawaited(
        AiCostTracker.event(
          feature: 'audio_cache',
          event: 'audio_cache_miss',
          requestId: cacheKey,
          extra: {'text_length': normalized.length, 'remote_checked': true},
        ),
      );
      return null;
    }
  }

  /// Imports PCM that was generated once as a shared course asset. This is a
  /// local cache write only: it never contacts Gemini and never uploads a
  /// learner-specific mirror. The shared object itself remains in the course
  /// asset bucket and is downloaded by the deck importer.
  Future<List<int>?> cacheLocally({
    required String text,
    required List<int> bytes,
    required String contentItemId,
    String? voiceName,
    bool slow = false,
  }) async {
    final normalized = text.trim().replaceAll(RegExp(r'\s+'), ' ');
    final persona = _personaForVoice(voiceName);
    if (normalized.isEmpty || persona == null || !_validPcm(bytes)) {
      return null;
    }
    final cacheKey = cacheKeyFor(
      text: normalized,
      voiceName: persona.voiceName,
      slow: slow,
    );
    await _writeLocal(cacheKey, bytes);
    unawaited(
      AiCostTracker.record(
        provider: 'local',
        model: 'shared-course-audio',
        feature: contentItemId,
        event: 'shared_audio_imported_local',
        requestId: cacheKey,
        cacheHit: true,
        extra: {'text_length': normalized.length},
      ),
    );
    return bytes;
  }

  /// Makes sure an already-rendered local clip has its private Supabase
  /// mirror. Generation and playback never depend on this call succeeding,
  /// but retrying it on every deck preparation closes the old gap where a
  /// successful local render could be lost on reinstall if the first upload
  /// was interrupted.
  Future<bool> ensureRemote({
    required String text,
    required String contentItemId,
    required String voiceName,
    required List<int> bytes,
    bool slow = false,
  }) async {
    final normalized = text.trim().replaceAll(RegExp(r'\s+'), ' ');
    if (normalized.isEmpty || bytes.isEmpty || bytes.length.isOdd) return false;
    final persona = _personaForVoice(voiceName);
    final userId = _currentUserId;
    if (persona == null || userId == null) {
      // Anonymous/development sessions intentionally remain local-first.
      return true;
    }
    final cacheKey = cacheKeyFor(
      text: normalized,
      voiceName: persona.voiceName,
      slow: slow,
    );
    final storagePath = storagePathFor(userId: userId, cacheKey: cacheKey);
    final client = Supabase.instance.client;
    try {
      try {
        await client.storage
            .from(_bucket)
            .uploadBinary(
              storagePath,
              Uint8List.fromList(_encodeStored(bytes)),
              fileOptions: const FileOptions(
                contentType: 'application/gzip',
                // Keep the mirror compatible with buckets that allow insert
                // but intentionally deny object updates. A duplicate object
                // is already the exact cache-keyed clip we need.
                upsert: false,
              ),
            );
      } catch (_) {
        final existing = await client.storage
            .from(_bucket)
            .download(storagePath)
            .timeout(const Duration(seconds: 8));
        if (!_validPcm(_decodeStored(existing))) rethrow;
      }
      await client.from('vocabulary_audio_cache').upsert({
        'user_id': userId,
        'cache_key': cacheKey,
        'content_item_id': contentItemId,
        'spoken_text': normalized,
        'voice_name': persona.voiceName,
        'storage_path': storagePath,
        'sha256': sha256.convert(bytes).toString(),
        'bytes': _encodeStored(bytes).length,
        'sample_rate_hz': outputSampleRateHz,
        'channels': 1,
        'encoding': _storedEncoding,
        'updated_at': DateTime.now().toUtc().toIso8601String(),
      }, onConflict: 'user_id,cache_key');
      unawaited(
        AiCostTracker.event(
          feature: contentItemId,
          event: 'audio_cache_mirrored_remote',
          requestId: cacheKey,
          extra: {'stored_bytes': _encodeStored(bytes).length},
        ),
      );
      return true;
    } catch (error) {
      debugPrint(
        'GeminiLiveAudioService: private audio mirror pending: $error',
      );
      unawaited(
        AiCostTracker.event(
          feature: contentItemId,
          event: 'audio_cache_mirror_failed',
          requestId: cacheKey,
          extra: {'error_type': error.runtimeType.toString()},
        ),
      );
      return false;
    }
  }

  /// Legacy compatibility hook. It only checks local/private cached objects;
  /// it never generates or prewarms audio.
  Future<void> warmDeck({
    required List<({String text, String contentItemId})> items,
    String? voiceName,
  }) async {
    if (items.isEmpty) return;
    for (final item in items) {
      await loadCached(text: item.text, voiceName: voiceName);
    }
  }

  /// Removes the private audio clips belonging to one generated content item.
  /// The lesson row itself is untouched, so revisiting it simply regenerates
  /// the missing clips with the currently selected tutor voice.
  Future<void> removeCachedAudio({required String contentItemId}) async {
    final userId = _currentUserId;
    if (userId == null || contentItemId.isEmpty) return;
    final client = Supabase.instance.client;
    try {
      final rows = await client
          .from('vocabulary_audio_cache')
          .select('cache_key, storage_path')
          .eq('user_id', userId)
          .eq('content_item_id', contentItemId);
      final cacheKeys = <String>[];
      final storagePaths = <String>[];
      for (final row in rows.whereType<Map>()) {
        final cacheKey = row['cache_key']?.toString();
        final storagePath = row['storage_path']?.toString();
        if (cacheKey != null) cacheKeys.add(cacheKey);
        if (storagePath != null) storagePaths.add(storagePath);
      }
      if (storagePaths.isNotEmpty) {
        await client.storage.from(_bucket).remove(storagePaths);
      }
      await client
          .from('vocabulary_audio_cache')
          .delete()
          .eq('user_id', userId)
          .eq('content_item_id', contentItemId);
      for (final cacheKey in cacheKeys) {
        try {
          await File('${(await _directory).path}/$cacheKey.pcm').delete();
        } catch (_) {}
      }
    } catch (error) {
      debugPrint(
        'GeminiLiveAudioService: private audio removal skipped: $error',
      );
    }
  }

  Future<List<int>?> _resolveUnshared(
    String text, {
    required String contentItemId,
    required TutorPersona persona,
    required String cacheKey,
    required bool slow,
    required bool checkRemote,
  }) async {
    final local = await _readLocal(cacheKey);
    if (_validPcm(local)) return local;

    final userId = _currentUserId;
    final storagePath = userId == null
        ? null
        : storagePathFor(userId: userId, cacheKey: cacheKey);
    if (checkRemote && storagePath != null) {
      try {
        final remote = await Supabase.instance.client.storage
            .from(_bucket)
            .download(storagePath)
            .timeout(const Duration(seconds: 3));
        final bytes = _decodeStored(remote);
        if (_validPcm(bytes)) {
          await _writeLocal(cacheKey, bytes);
          unawaited(
            AiCostTracker.record(
              provider: 'google',
              model: _model,
              feature: contentItemId,
              event: 'live_audio_cache_hit_remote',
              requestId: cacheKey,
              cacheHit: true,
              outputAudioSeconds: bytes.length / 2 / outputSampleRateHz,
              extra: {'text_length': text.length},
            ),
          );
          return bytes;
        }
      } catch (_) {
        // A miss is expected on a learner's first encounter with a phrase.
      }
    }

    final generationClock = Stopwatch()..start();
    unawaited(
      AiCostTracker.event(
        feature: contentItemId,
        event: 'audio_provider_call_started',
        requestId: cacheKey,
        extra: {'model': _model, 'text_length': text.length},
      ),
    );
    // A healthy call finishes in a handful of seconds (verified directly:
    // 4-8s typical). 35s per attempt meant a genuinely stuck story-narration
    // line used to be retried by the old narration path and could take up to
    // ~2 minutes to finally surface an error — long enough that a learner
    // assumed playback silently froze. The generation path now makes one
    // bounded attempt only.
    //
    // Story PCM is allowed to use its own bounded audio socket while Marie's
    // conversational socket is active. The old guard returned null whenever
    // the learner had Marie connected, which made the exact keyword/grammar
    // workflow we want (Live help + PCM story playback) impossible.
    if (GeminiLiveService.hasActiveSocket) {
      unawaited(
        AiCostTracker.event(
          feature: contentItemId,
          event: 'audio_generation_concurrent_live_socket',
          requestId: cacheKey,
          extra: {'model': _model, 'text_length': text.length},
        ),
      );
    }
    // Keep the timeout inside _generateLive so its finally block can cancel
    // the WebSocket before a retry starts. Wrapping the Future from outside
    // lets the old socket linger for its full 30-second turn timeout, which
    // made the next sentence wait or fail even though the caller had moved on.
    final generated = await _generateLive(
      text,
      persona: persona,
      slow: slow,
      traceFeature: contentItemId,
    );
    generationClock.stop();
    if (!_validPcm(generated)) {
      unawaited(
        AiCostTracker.record(
          provider: 'google',
          model: _model,
          feature: contentItemId,
          event: 'live_audio_generation_failed',
          requestId: cacheKey,
          success: false,
          extra: {
            'text_length': text.length,
            'billing_unknown': true,
            'provider_response_audio_seconds': 0,
          },
        ),
      );
      unawaited(
        AiCostTracker.event(
          feature: contentItemId,
          event: 'audio_provider_call_failed',
          requestId: cacheKey,
          extra: {'elapsed_ms': generationClock.elapsedMilliseconds},
        ),
      );
      return null;
    }
    final generatedBytes = generated!;
    unawaited(
      AiCostTracker.record(
        provider: 'google',
        model: _model,
        feature: contentItemId,
        event: 'live_audio_generation',
        requestId: cacheKey,
        outputAudioSeconds: generatedBytes.length / 2 / outputSampleRateHz,
        extra: {'text_length': text.length},
      ),
    );
    unawaited(
      AiCostTracker.event(
        feature: contentItemId,
        event: 'audio_provider_call_finished',
        requestId: cacheKey,
        extra: {
          'elapsed_ms': generationClock.elapsedMilliseconds,
          'output_pcm_bytes': generatedBytes.length,
        },
      ),
    );
    await _writeLocal(cacheKey, generatedBytes);

    if (userId != null && storagePath != null) {
      final client = Supabase.instance.client;
      try {
        await client.storage
            .from(_bucket)
            .uploadBinary(
              storagePath,
              Uint8List.fromList(_encodeStored(generatedBytes)),
              fileOptions: const FileOptions(
                contentType: 'application/gzip',
                upsert: false,
              ),
            );
      } catch (error) {
        debugPrint(
          'GeminiLiveAudioService: private audio upload skipped: $error',
        );
      }
      try {
        await client.from('vocabulary_audio_cache').upsert({
          'user_id': userId,
          'cache_key': cacheKey,
          'content_item_id': contentItemId,
          'spoken_text': text,
          'voice_name': persona.voiceName,
          'storage_path': storagePath,
          'sha256': sha256.convert(generatedBytes).toString(),
          'bytes': _encodeStored(generatedBytes).length,
          'sample_rate_hz': 24000,
          'channels': 1,
          'encoding': _storedEncoding,
          'updated_at': DateTime.now().toUtc().toIso8601String(),
        }, onConflict: 'user_id,cache_key');
      } catch (error) {
        debugPrint(
          'GeminiLiveAudioService: private audio index skipped: $error',
        );
      }
    }
    return generatedBytes;
  }

  TutorPersona? _personaForVoice(String? voiceName) {
    if (voiceName == null || voiceName.isEmpty) return ActiveTutor.current;
    for (final persona in TutorPersona.all) {
      if (persona.voiceName == voiceName) return persona;
    }
    return null;
  }

  String? get _currentUserId {
    try {
      return Supabase.instance.client.auth.currentUser?.id;
    } catch (_) {
      return null;
    }
  }

  Future<Directory> get _directory async {
    if (_cacheDir != null) return _cacheDir!;
    final base = await getApplicationSupportDirectory();
    final directory = Directory('${base.path}/gemini_live_audio_cache');
    if (!await directory.exists()) await directory.create(recursive: true);
    return _cacheDir = directory;
  }

  Future<List<int>?> _readLocal(String cacheKey) async {
    try {
      final file = File('${(await _directory).path}/$cacheKey.pcm');
      if (await file.exists()) return _decodeStored(await file.readAsBytes());
    } catch (_) {}
    return null;
  }

  Future<void> _writeLocal(String cacheKey, List<int> bytes) async {
    try {
      await File(
        '${(await _directory).path}/$cacheKey.pcm',
      ).writeAsBytes(_encodeStored(bytes), flush: false);
    } catch (_) {}
  }

  /// Lossless storage compression. Playback always receives the original
  /// PCM16 bytes, while local files and Supabase objects occupy less space.
  /// The decoder accepts old raw-PCM objects so existing caches remain valid.
  List<int> _encodeStored(List<int> pcm) => gzip.encode(pcm);

  List<int> _decodeStored(List<int> stored) {
    if (stored.length >= 2 && stored[0] == 0x1f && stored[1] == 0x8b) {
      try {
        return gzip.decode(stored);
      } catch (_) {
        return const <int>[];
      }
    }
    return stored;
  }

  bool _validPcm(List<int>? bytes) =>
      bytes != null && bytes.isNotEmpty && bytes.length.isEven;

  Future<List<int>?> _generateLive(
    String text, {
    required TutorPersona persona,
    required bool slow,
    String? systemInstruction,
    String? traceFeature,
  }) async {
    late final String token;
    try {
      token = await GeminiLiveTokenService.fetch();
    } catch (_) {
      return null;
    }
    final channel = WebSocketChannel.connect(
      Uri.parse(
        'wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1alpha.GenerativeService.BidiGenerateContentConstrained?access_token=${Uri.encodeQueryComponent(token)}',
      ),
    );
    final setupComplete = Completer<void>();
    final turnComplete = Completer<void>();
    final audio = <int>[];
    final outputTranscript = StringBuffer();
    late final StreamSubscription subscription;

    // Only one of these two completers ends up actually awaited below — if
    // setupComplete fails, the code throws out of that await and never
    // reaches `await turnComplete.future` at all. Without a catchError
    // attached here, that second, never-awaited completeError becomes an
    // "Uncaught (in zone) error" that Sentry reports as a crash even though
    // it changes nothing functionally: the real error is already handled by
    // this function's own try/catch a few lines down.
    void fail(Object error, [StackTrace? stackTrace]) {
      if (!setupComplete.isCompleted) {
        setupComplete.completeError(error, stackTrace);
        setupComplete.future.catchError((_) {});
      }
      if (!turnComplete.isCompleted) {
        turnComplete.completeError(error, stackTrace);
        turnComplete.future.catchError((_) {});
      }
    }

    subscription = channel.stream.listen(
      (message) {
        try {
          final json =
              jsonDecode(
                    message is String
                        ? message
                        : utf8.decode(message as List<int>),
                  )
                  as Map<String, dynamic>;
          final usageMetadata = json['usageMetadata'];
          if (usageMetadata is Map && traceFeature != null) {
            unawaited(
              AiCostTracker.event(
                feature: traceFeature,
                event: 'live_audio_usage_metadata',
                extra: {
                  'provider_prompt_tokens': usageMetadata['promptTokenCount'],
                  'provider_response_tokens':
                      usageMetadata['responseTokenCount'] ??
                      usageMetadata['candidatesTokenCount'],
                  'provider_total_tokens': usageMetadata['totalTokenCount'],
                  'cached_content_token_count':
                      usageMetadata['cachedContentTokenCount'],
                },
              ),
            );
          }
          final error = json['error'];
          if (error is Map) {
            fail(
              StateError(error['message']?.toString() ?? 'Gemini Live error'),
            );
            return;
          }
          if (json.containsKey('setupComplete') && !setupComplete.isCompleted) {
            setupComplete.complete();
          }
          final serverContent = json['serverContent'];
          if (serverContent is! Map) return;
          final outputTranscription = serverContent['outputTranscription'];
          if (outputTranscription is Map) {
            final text = outputTranscription['text'];
            if (text is String) outputTranscript.write(text);
          }
          final modelTurn = serverContent['modelTurn'];
          final parts = modelTurn is Map ? modelTurn['parts'] : null;
          if (parts is List) {
            for (final part in parts) {
              if (part is! Map) continue;
              final inlineData = part['inlineData'];
              final data = inlineData is Map ? inlineData['data'] : null;
              if (data is String) audio.addAll(base64Decode(data));
            }
          }
          if (serverContent['turnComplete'] == true &&
              !turnComplete.isCompleted) {
            turnComplete.complete();
          }
        } catch (error, stackTrace) {
          fail(error, stackTrace);
        }
      },
      onError: fail,
      onDone: () {
        if (!turnComplete.isCompleted) {
          fail(StateError('Gemini Live audio socket closed early'));
        }
      },
    );

    try {
      channel.sink.add(
        jsonEncode({
          'setup': {
            'model': _model,
            'generationConfig': {
              'responseModalities': ['AUDIO'],
              // Pronunciation is a deterministic read-aloud task, not a
              // creative conversation. A low temperature reduces semantic
              // replies on lines such as “Merci…” or “Bonne journée.”.
              'temperature': 0.1,
              'speechConfig': {
                'voiceConfig': {
                  'prebuiltVoiceConfig': {'voiceName': persona.voiceName},
                },
              },
            },
            'systemInstruction': {
              'parts': [
                {
                  'text':
                      systemInstruction ??
                      pronunciationSystemInstruction(slow: slow),
                },
              ],
            },
            // Ask Live for the text it believes it spoke. When available,
            // _generateLive compares this transcript with the immutable
            // lesson script and rejects a semantic reply or paraphrase.
            'outputAudioTranscription': <String, dynamic>{},
          },
        }),
      );
      // Do not let one unavailable Live turn block the rest of the deck. A
      // healthy short pronunciation response is normally ready well below
      // this bound; a later explicit pass can retry a missing clip.
      await setupComplete.future.timeout(const Duration(seconds: 8));
      channel.sink.add(jsonEncode(realtimeTextMessage(text)));
      await turnComplete.future.timeout(const Duration(seconds: 8));
      final transcript = _normalisePronunciationTranscript(
        outputTranscript.toString(),
      );
      final expected = _normalisePronunciationTranscript(text);
      if (transcript.isNotEmpty && transcript != expected) {
        debugPrint(
          'GeminiLiveAudioService: rejected mismatched pronunciation output '
          '(expected "$expected", received "$transcript")',
        );
        return null;
      }
      return _validPcm(audio) ? List<int>.unmodifiable(audio) : null;
    } catch (error) {
      debugPrint('GeminiLiveAudioService: Live generation failed: $error');
      return null;
    } finally {
      await subscription.cancel();
      await channel.sink.close();
    }
  }

  static String _normalisePronunciationTranscript(String value) => value
      .toLowerCase()
      .replaceAll(RegExp(r'''[.,!?;:«»"'’()\[\]{}-]'''), '')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();
}
