part of 'writing_course.dart';

WritingCourseStep _arrange(String french, String english) => WritingCourseStep(
  prompt: 'Build the sentence',
  promptEnglish: english,
  target: french,
  tokens: french.split(' '),
  tokenMeanings: _meaningsFor(french.split(' ')),
  kind: WritingInputKind.arrange,
  tip: 'Start with the person or polite opening.',
);

WritingCourseStep _complete({
  required String sentence,
  required String english,
  required String answer,
  required List<String> choices,
  String? partner,
}) => WritingCourseStep(
  prompt: sentence,
  promptEnglish: english,
  target: answer,
  choices: choices,
  choiceMeanings: _meaningsFor(choices),
  kind: WritingInputKind.choice,
  partnerFrench: partner,
  partnerEnglish: partner == null
      ? null
      : _partnerMeanings[_meaningKey(partner)],
  tip: 'Choose the word that fits the meaning and grammar.',
);

WritingCourseStep _beat({
  required String partner,
  required String partnerEnglish,
  required String goal,
  required String target,
  required String starter,
  required List<String> suggestions,
}) => WritingCourseStep(
  prompt: 'Write your reply',
  promptEnglish: goal,
  target: target,
  kind: WritingInputKind.text,
  partnerFrench: partner,
  partnerEnglish: partnerEnglish,
  goal: goal,
  starter: starter,
  suggestions: suggestions,
  suggestionMeanings: _meaningsFor(suggestions),
  tip: 'Complete the goal in one short, polite message.',
);

String _meaningKey(String value) =>
    value.toLowerCase().replaceAll(RegExp(r"[.,!?;:«»’']"), '').trim();

List<String> _meaningsFor(Iterable<String> values) => [
  for (final value in values)
    _seedMeanings[_meaningKey(value)] ??
        (_meaningKey(value).isEmpty ? '' : 'French phrase'),
];

// Short learner-facing meanings for the authored A1 bank. Generated lessons
// carry the same field from the model and are validated before they appear.
const _seedMeanings = <String, String>{
  'bonjour': 'hello',
  'je': 'I',
  'mappelle': 'my name is',
  'alex': 'Alex',
  'jhabite': 'I live',
  'à': 'in / at',
  'toronto': 'Toronto',
  'parle': 'speak',
  'anglais': 'English',
  'japprends': 'I am learning',
  'le': 'the',
  'les': 'the',
  'français': 'French',
  'enchanté': 'nice to meet you',
  'de': 'to',
  'vous': 'you',
  'rencontrer': 'meet',
  'voudrais': 'would like',
  'un': 'a / one',
  'café': 'coffee',
  'un café': 'a coffee',
  'une gare': 'a station',
  'un ami': 'a friend',
  'avec': 'with',
  'du': 'some / of the',
  'lait': 'milk',
  'sil': 'if it',
  'plaît': 'pleases',
  'sans': 'without',
  'sucre': 'sugar',
  'merci': 'thank you',
  'cest': 'it is',
  'pour': 'for',
  'ici': 'here',
  'bonne': 'good',
  'journée': 'day',
  'excusez-moi': 'excuse me',
  'pouvez-vous': 'can you',
  'maider': 'help me',
  'ne': 'not',
  'comprends': 'understand',
  'pas': 'not',
  'répéter': 'repeat',
  'plus': 'more',
  'lentement': 'slowly',
  'beaucoup': 'a lot / very much',
  'votre': 'your',
  'aide': 'help',
  'où': 'where',
  'est': 'is',
  'la': 'the',
  'gare': 'station',
  'station': 'station',
  'près': 'near',
  'dici': 'from here',
  'tournez': 'turn',
  'gauche': 'left',
  'continuez': 'continue',
  'tout': 'all / straight',
  'droit': 'straight',
  'directions': 'directions',
  'me': 'myself',
  'lève': 'get up',
  'sept': 'seven',
  'heures': 'o’clock / hours',
  'bois': 'drink',
  'vais': 'go',
  'au': 'to the',
  'travail': 'work',
  'rentre': 'return',
  'maison': 'home / house',
  'couche': 'go to bed',
  'dix': 'ten',
  'addition': 'bill',
  'adresse': 'address',
  'carte': 'card',
  'table': 'table',
  'porte': 'door',
  'année': 'year',
  'chaise': 'chair',
  'ville': 'city',
  'chambre': 'bedroom',
  'rue': 'street',
  'rues': 'streets',
  'cartes': 'cards',
  'cuisine': 'kitchen',
  'banque': 'bank',
  'voiture': 'car',
  'fenêtre': 'window',
  'semaine': 'week',
  'famille': 'family',
  'aujourdhui': 'today',
  'pomme': 'apple',
  'demain': 'tomorrow',
  'nom': 'name',
  'question': 'question',
  'hier': 'yesterday',
  'vite': 'quickly',
  'bientôt': 'soon',
  'amie': 'friend',
  'frère': 'brother',
  'bus': 'bus',
  'gentille': 'kind',
  'petit': 'small',
  'montréal': 'Montreal',
  'manger': 'eat',
  'matin': 'morning',
  'train': 'train',
  'pain': 'bread',
  'livre': 'book',
  'billet': 'ticket',
  'stylo': 'pen',
  'portes': 'doors',
  'pommes': 'apples',
  'jour': 'day',
  'pays': 'country',
  'cest tout': 'that is all',
  'daccord': 'okay',
  'sil vous plaît': 'please',
  'du lait': 'some milk',
  'sans sucre': 'without sugar',
  'je suis libre': 'I am free',
  'samedi': 'Saturday',
  'libre': 'free',
  'aller': 'go',
  'au cinéma': 'to the cinema',
  'cest bien': 'is that good?',
  'la gare': 'the station',
  'une chemise': 'a shirt',
  'je la prends': 'I will take it',
  'à gauche': 'to the left',
  'tout droit': 'straight ahead',
  'pour votre aide': 'for your help',
  'par carte': 'by card',
  'un rendez-vous': 'an appointment',
  'à samedi': 'see you Saturday',
  'à mardi': 'see you Tuesday',
  'dix heures': 'ten o’clock',
  'me convient': 'works for me',
  'une': 'a / one',
  'chemise': 'shirt',
  'bleue': 'blue',
  'taille': 'size',
  'moyenne': 'medium',
  'prends': 'take',
  'paie': 'pay',
  'par': 'by',
  'rendez-vous': 'appointment',
  'mardi': 'Tuesday',
  'convient': 'suits / works',
};

const _partnerMeanings = <String, String>{
  'tu veux boire quoi': 'What do you want to drink?',
};

WritingCourseLesson _guided({
  required String id,
  required String title,
  required String subtitle,
  required IconData icon,
  required List<WritingCourseStep> steps,
}) => WritingCourseLesson(
  id: id,
  title: title,
  subtitle: subtitle,
  level: 'A1',
  icon: icon,
  mode: WritingCourseMode.guided,
  steps: steps,
);

WritingCourseLesson _choiceLesson({
  required String id,
  required String title,
  required String subtitle,
  required IconData icon,
  required List<WritingCourseStep> steps,
}) => WritingCourseLesson(
  id: id,
  title: title,
  subtitle: subtitle,
  level: 'A1',
  icon: icon,
  mode: WritingCourseMode.complete,
  steps: steps,
);

WritingCourseLesson _roleplay({
  required String id,
  required String title,
  required String subtitle,
  required String goal,
  required IconData icon,
  required List<WritingCourseStep> steps,
}) => WritingCourseLesson(
  id: id,
  title: title,
  subtitle: subtitle,
  level: 'A1',
  icon: icon,
  mode: WritingCourseMode.roleplay,
  goal: goal,
  steps: steps,
);

/// Five reviewable starter lessons in each Writing mode. They remain local and
/// instant; generated lessons are appended only after validation.
abstract final class WritingCourseCatalog {
  static final lessons = <WritingCourseLesson>[
    _guided(
      id: 'writing_guided_a1_01_introduce',
      title: 'Introduce yourself',
      subtitle: 'Build five short sentences about who you are.',
      icon: Icons.person_outline_rounded,
      steps: [
        _arrange('Bonjour, je m’appelle Alex.', 'Hello, my name is Alex.'),
        _arrange('J’habite à Toronto.', 'I live in Toronto.'),
        _arrange('Je parle anglais.', 'I speak English.'),
        _arrange('J’apprends le français.', 'I am learning French.'),
        _arrange('Enchanté de vous rencontrer.', 'Nice to meet you.'),
      ],
    ),
    _guided(
      id: 'writing_guided_a1_02_coffee',
      title: 'Order a coffee',
      subtitle: 'Build a polite café order one line at a time.',
      icon: Icons.local_cafe_outlined,
      steps: [
        _arrange(
          'Bonjour, je voudrais un café.',
          'Hello, I would like a coffee.',
        ),
        _arrange('Avec du lait, s’il vous plaît.', 'With milk, please.'),
        _arrange('Sans sucre, merci.', 'Without sugar, thank you.'),
        _arrange('C’est pour ici.', 'It is for here.'),
        _arrange('Merci, bonne journée.', 'Thank you, have a nice day.'),
      ],
    ),
    _guided(
      id: 'writing_guided_a1_03_help',
      title: 'Ask for help',
      subtitle: 'Write clear, polite requests for everyday problems.',
      icon: Icons.help_outline_rounded,
      steps: [
        _arrange(
          'Excusez-moi, pouvez-vous m’aider ?',
          'Excuse me, can you help me?',
        ),
        _arrange('Je ne comprends pas.', 'I do not understand.'),
        _arrange('Pouvez-vous répéter ?', 'Can you repeat?'),
        _arrange('Plus lentement, s’il vous plaît.', 'More slowly, please.'),
        _arrange(
          'Merci beaucoup pour votre aide.',
          'Thank you very much for your help.',
        ),
      ],
    ),
    _guided(
      id: 'writing_guided_a1_04_directions',
      title: 'Ask for directions',
      subtitle: 'Build useful questions for finding a place.',
      icon: Icons.signpost_outlined,
      steps: [
        _arrange('Où est la gare ?', 'Where is the station?'),
        _arrange('La gare est près d’ici.', 'The station is near here.'),
        _arrange('Tournez à gauche.', 'Turn left.'),
        _arrange('Continuez tout droit.', 'Continue straight ahead.'),
        _arrange('Merci pour les directions.', 'Thank you for the directions.'),
      ],
    ),
    _guided(
      id: 'writing_guided_a1_05_routine',
      title: 'My daily routine',
      subtitle: 'Put five everyday actions into clear sentences.',
      icon: Icons.wb_sunny_outlined,
      steps: [
        _arrange('Je me lève à sept heures.', 'I get up at seven.'),
        _arrange('Je bois un café.', 'I drink a coffee.'),
        _arrange('Je vais au travail.', 'I go to work.'),
        _arrange('Je rentre à la maison.', 'I return home.'),
        _arrange('Je me couche à dix heures.', 'I go to bed at ten.'),
      ],
    ),
    _choiceLesson(
      id: 'writing_complete_a1_01_cafe',
      title: 'At the café',
      subtitle: 'Choose the words that complete a simple order.',
      icon: Icons.local_cafe_outlined,
      steps: [
        _complete(
          sentence: 'Je voudrais ___, s’il te plaît.',
          english: 'I would like a coffee, please.',
          answer: 'un café',
          choices: ['un café', 'une gare', 'un ami'],
          partner: 'Tu veux boire quoi ?',
        ),
        _complete(
          sentence: 'Avec du ___, s’il vous plaît.',
          english: 'With milk, please.',
          answer: 'lait',
          choices: ['lait', 'train', 'livre'],
        ),
        _complete(
          sentence: 'Je voudrais payer par ___.',
          english: 'I would like to pay by card.',
          answer: 'carte',
          choices: ['carte', 'table', 'porte'],
        ),
        _complete(
          sentence: 'L’___, s’il vous plaît.',
          english: 'The bill, please.',
          answer: 'addition',
          choices: ['addition', 'adresse', 'année'],
        ),
        _complete(
          sentence: 'Merci, bonne ___.',
          english: 'Thank you, have a nice day.',
          answer: 'journée',
          choices: ['journée', 'chaise', 'ville'],
        ),
      ],
    ),
    _choiceLesson(
      id: 'writing_complete_a1_02_home',
      title: 'Around the house',
      subtitle: 'Complete sentences about rooms and objects.',
      icon: Icons.home_outlined,
      steps: [
        _complete(
          sentence: 'Je dors dans la ___.',
          english: 'I sleep in the bedroom.',
          answer: 'chambre',
          choices: ['chambre', 'gare', 'rue'],
        ),
        _complete(
          sentence: 'La table est dans la ___.',
          english: 'The table is in the kitchen.',
          answer: 'cuisine',
          choices: ['cuisine', 'banque', 'voiture'],
        ),
        _complete(
          sentence: 'J’ouvre la ___.',
          english: 'I open the window.',
          answer: 'fenêtre',
          choices: ['fenêtre', 'semaine', 'famille'],
        ),
        _complete(
          sentence: 'Le livre est sur la ___.',
          english: 'The book is on the table.',
          answer: 'table',
          choices: ['table', 'ville', 'gare'],
        ),
        _complete(
          sentence: 'Je rentre à la ___.',
          english: 'I return home.',
          answer: 'maison',
          choices: ['maison', 'station', 'question'],
        ),
      ],
    ),
    _choiceLesson(
      id: 'writing_complete_a1_03_time',
      title: 'Days and times',
      subtitle: 'Choose the time word that makes each message clear.',
      icon: Icons.schedule_outlined,
      steps: [
        _complete(
          sentence: 'Je travaille ___.',
          english: 'I work today.',
          answer: 'aujourd’hui',
          choices: ['aujourd’hui', 'pomme', 'porte'],
        ),
        _complete(
          sentence: 'Je voyage ___.',
          english: 'I travel tomorrow.',
          answer: 'demain',
          choices: ['demain', 'café', 'nom'],
        ),
        _complete(
          sentence: 'J’ai étudié ___.',
          english: 'I studied yesterday.',
          answer: 'hier',
          choices: ['hier', 'ici', 'vite'],
        ),
        _complete(
          sentence: 'Le cours commence à huit ___.',
          english: 'The class starts at eight o’clock.',
          answer: 'heures',
          choices: ['heures', 'rues', 'cartes'],
        ),
        _complete(
          sentence: 'À ___ !',
          english: 'See you soon!',
          answer: 'bientôt',
          choices: ['bientôt', 'beaucoup', 'bonjour'],
        ),
      ],
    ),
    _choiceLesson(
      id: 'writing_complete_a1_04_people',
      title: 'People I know',
      subtitle: 'Complete short descriptions of family and friends.',
      icon: Icons.people_outline_rounded,
      steps: [
        _complete(
          sentence: 'Marie est mon ___.',
          english: 'Marie is my friend.',
          answer: 'amie',
          choices: ['amie', 'ville', 'table'],
        ),
        _complete(
          sentence: 'Paul est mon ___.',
          english: 'Paul is my brother.',
          answer: 'frère',
          choices: ['frère', 'café', 'bus'],
        ),
        _complete(
          sentence: 'Ma mère est très ___.',
          english: 'My mother is very kind.',
          answer: 'gentille',
          choices: ['gentille', 'petit', 'demain'],
        ),
        _complete(
          sentence: 'Mon ami habite à ___.',
          english: 'My friend lives in Montreal.',
          answer: 'Montréal',
          choices: ['Montréal', 'manger', 'matin'],
        ),
        _complete(
          sentence: 'Nous sommes une petite ___.',
          english: 'We are a small family.',
          answer: 'famille',
          choices: ['famille', 'fenêtre', 'semaine'],
        ),
      ],
    ),
    _choiceLesson(
      id: 'writing_complete_a1_05_travel',
      title: 'Getting around',
      subtitle: 'Complete useful sentences for a short trip.',
      icon: Icons.train_outlined,
      steps: [
        _complete(
          sentence: 'Je prends le ___.',
          english: 'I take the train.',
          answer: 'train',
          choices: ['train', 'pain', 'livre'],
        ),
        _complete(
          sentence: 'Où est la ___ ?',
          english: 'Where is the station?',
          answer: 'gare',
          choices: ['gare', 'carte', 'chaise'],
        ),
        _complete(
          sentence: 'Je voudrais un ___.',
          english: 'I would like a ticket.',
          answer: 'billet',
          choices: ['billet', 'lait', 'stylo'],
        ),
        _complete(
          sentence: 'Le bus arrive à neuf ___.',
          english: 'The bus arrives at nine o’clock.',
          answer: 'heures',
          choices: ['heures', 'portes', 'pommes'],
        ),
        _complete(
          sentence: 'Je vais au centre-___.',
          english: 'I am going downtown.',
          answer: 'ville',
          choices: ['ville', 'jour', 'pays'],
        ),
      ],
    ),
    _roleplay(
      id: 'writing_roleplay_a1_01_cafe',
      title: 'At the café',
      subtitle: 'Order a drink and close the exchange politely.',
      goal: 'Order a coffee and ask for the bill.',
      icon: Icons.restaurant_outlined,
      steps: [
        _beat(
          partner: 'Bonjour ! Vous désirez ?',
          partnerEnglish: 'Hello! What would you like?',
          goal: 'Reply politely and order a coffee.',
          target: 'Bonjour, je voudrais un café, s’il vous plaît.',
          starter: 'Bonjour, je voudrais…',
          suggestions: ['un café', 's’il vous plaît'],
        ),
        _beat(
          partner: 'Avec du lait ou du sucre ?',
          partnerEnglish: 'With milk or sugar?',
          goal: 'Ask for milk but no sugar.',
          target: 'Avec du lait, mais sans sucre, merci.',
          starter: 'Avec…',
          suggestions: ['du lait', 'sans sucre'],
        ),
        _beat(
          partner: 'C’est tout ?',
          partnerEnglish: 'Is that all?',
          goal: 'Confirm that is all.',
          target: 'Oui, c’est tout, merci.',
          starter: 'Oui…',
          suggestions: ['c’est tout', 'merci'],
        ),
        _beat(
          partner: 'Très bien. Autre chose ?',
          partnerEnglish: 'Very good. Anything else?',
          goal: 'Ask for the bill.',
          target: 'L’addition, s’il vous plaît.',
          starter: 'L’addition…',
          suggestions: ['s’il vous plaît'],
        ),
      ],
    ),
    _roleplay(
      id: 'writing_roleplay_a1_02_friend',
      title: 'Make plans with a friend',
      subtitle: 'Choose a simple activity, day, and time by message.',
      goal: 'Agree on an activity and a time.',
      icon: Icons.event_available_outlined,
      steps: [
        _beat(
          partner: 'Salut ! Tu es libre samedi ?',
          partnerEnglish: 'Hi! Are you free Saturday?',
          goal: 'Say yes and greet your friend.',
          target: 'Salut ! Oui, je suis libre samedi.',
          starter: 'Salut ! Oui…',
          suggestions: ['je suis libre', 'samedi'],
        ),
        _beat(
          partner: 'Tu veux aller au cinéma ?',
          partnerEnglish: 'Do you want to go to the cinema?',
          goal: 'Accept the invitation.',
          target: 'Oui, je veux aller au cinéma.',
          starter: 'Oui, je veux…',
          suggestions: ['aller', 'au cinéma'],
        ),
        _beat(
          partner: 'À quelle heure ?',
          partnerEnglish: 'At what time?',
          goal: 'Suggest seven o’clock.',
          target: 'À sept heures, c’est bien ?',
          starter: 'À sept heures…',
          suggestions: ['c’est bien ?'],
        ),
        _beat(
          partner: 'Parfait, à samedi !',
          partnerEnglish: 'Perfect, see you Saturday!',
          goal: 'Close the conversation.',
          target: 'Parfait, à samedi !',
          starter: 'Parfait…',
          suggestions: ['à samedi'],
        ),
      ],
    ),
    _roleplay(
      id: 'writing_roleplay_a1_03_directions',
      title: 'Find the station',
      subtitle: 'Ask for directions and confirm the route.',
      goal: 'Find the station using short written questions.',
      icon: Icons.signpost_outlined,
      steps: [
        _beat(
          partner: 'Bonjour, je peux vous aider ?',
          partnerEnglish: 'Hello, can I help you?',
          goal: 'Ask where the station is.',
          target: 'Bonjour, où est la gare, s’il vous plaît ?',
          starter: 'Bonjour, où est…',
          suggestions: ['la gare', 's’il vous plaît'],
        ),
        _beat(
          partner: 'La gare est près d’ici.',
          partnerEnglish: 'The station is near here.',
          goal: 'Ask if you should turn left.',
          target: 'Je tourne à gauche ?',
          starter: 'Je tourne…',
          suggestions: ['à gauche ?'],
        ),
        _beat(
          partner: 'Oui, puis continuez tout droit.',
          partnerEnglish: 'Yes, then continue straight.',
          goal: 'Confirm you understand.',
          target: 'D’accord, tout droit.',
          starter: 'D’accord…',
          suggestions: ['tout droit'],
        ),
        _beat(
          partner: 'La gare est à droite.',
          partnerEnglish: 'The station is on the right.',
          goal: 'Thank the person.',
          target: 'Merci beaucoup pour votre aide.',
          starter: 'Merci…',
          suggestions: ['beaucoup', 'pour votre aide'],
        ),
      ],
    ),
    _roleplay(
      id: 'writing_roleplay_a1_04_shop',
      title: 'At a shop',
      subtitle: 'Ask for an item, check the price, and pay.',
      goal: 'Buy one item politely.',
      icon: Icons.shopping_bag_outlined,
      steps: [
        _beat(
          partner: 'Bonjour, vous cherchez quelque chose ?',
          partnerEnglish: 'Hello, are you looking for something?',
          goal: 'Say you want a blue shirt.',
          target: 'Bonjour, je voudrais une chemise bleue.',
          starter: 'Bonjour, je voudrais…',
          suggestions: ['une chemise', 'bleue'],
        ),
        _beat(
          partner: 'Quelle taille ?',
          partnerEnglish: 'What size?',
          goal: 'Ask for a medium.',
          target: 'Une taille moyenne, s’il vous plaît.',
          starter: 'Une taille…',
          suggestions: ['moyenne', 's’il vous plaît'],
        ),
        _beat(
          partner: 'Voici. Elle coûte trente euros.',
          partnerEnglish: 'Here you are. It costs thirty euros.',
          goal: 'Say you will take it.',
          target: 'D’accord, je la prends.',
          starter: 'D’accord…',
          suggestions: ['je la prends'],
        ),
        _beat(
          partner: 'Vous payez comment ?',
          partnerEnglish: 'How are you paying?',
          goal: 'Say you are paying by card.',
          target: 'Je paie par carte, merci.',
          starter: 'Je paie…',
          suggestions: ['par carte', 'merci'],
        ),
      ],
    ),
    _roleplay(
      id: 'writing_roleplay_a1_05_appointment',
      title: 'Book an appointment',
      subtitle: 'Ask for a time and confirm the details.',
      goal: 'Book and confirm a simple appointment.',
      icon: Icons.calendar_month_outlined,
      steps: [
        _beat(
          partner: 'Bonjour, comment puis-je vous aider ?',
          partnerEnglish: 'Hello, how can I help you?',
          goal: 'Ask for an appointment.',
          target: 'Bonjour, je voudrais un rendez-vous.',
          starter: 'Bonjour, je voudrais…',
          suggestions: ['un rendez-vous'],
        ),
        _beat(
          partner: 'Vous êtes libre mardi ?',
          partnerEnglish: 'Are you free Tuesday?',
          goal: 'Say Tuesday works.',
          target: 'Oui, mardi me convient.',
          starter: 'Oui, mardi…',
          suggestions: ['me convient'],
        ),
        _beat(
          partner: 'À dix heures ?',
          partnerEnglish: 'At ten o’clock?',
          goal: 'Confirm the time.',
          target: 'Oui, à dix heures.',
          starter: 'Oui, à…',
          suggestions: ['dix heures'],
        ),
        _beat(
          partner: 'Parfait, à mardi.',
          partnerEnglish: 'Perfect, see you Tuesday.',
          goal: 'Thank them and close.',
          target: 'Merci beaucoup, à mardi.',
          starter: 'Merci…',
          suggestions: ['beaucoup', 'à mardi'],
        ),
      ],
    ),
  ];

  static List<WritingCourseLesson> forMode(WritingCourseMode mode) =>
      lessons.where((lesson) => lesson.mode == mode).toList(growable: false);
}
